### PR TITLE
Add config page for school forms, add default search date config points

### PR DESCRIPTION
**Pull request by routinet**

### CODE REVIEW

**Comment by routinet** [comment]
This is only to make the dates configurable.  There are other issues in this code which need to be addressed in the future.

**Review by fksaintil — APPROVED** [review]

**Comment by routinet** [comment]
Moving towards refactor of this section.

**Review by nathanielwoodland — APPROVED** [review]
Code looks good @routinet. However, I'm not 100% clear on the business need here, so I can't properly scrutinize if this is the best way to achieve the desired end result in Drupal (but maybe you don't need me scrutinizing everything you do!)

**Comment by routinet** [comment]
@nathanielwoodland all good.. we know this isn't the best.  This is a stop-gap, which also provided the impetus to spin up NYS-83 again.

**Pull request merged**
